/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        arcane: {
          50: '#F0F4FF',
          100: '#D9E2FB',
          200: '#B3C5F7',
          300: '#8DA7F3',
          400: '#5E7FED',
          500: '#3D5FE8',
          600: '#2A44C8',
          700: '#1E33A0',
          800: '#1523770',
          900: '#0D1850',
          950: '#070D30',
        },
        mystic: {
          50: '#F5F0FF',
          100: '#E8DBFF',
          200: '#D1B7FF',
          300: '#BA93FF',
          400: '#A06FFF',
          500: '#8B4FFF',
          600: '#7038E0',
          700: '#5828B0',
          800: '#401C80',
          900: '#281050',
        },
        ember: {
          50: '#FFF8E8',
          100: '#FFEAC8',
          200: '#FFD58F',
          300: '#FFBE5C',
          400: '#FFA82C',
          500: '#F0941A',
          600: '#C87610',
          700: '#A0580C',
          800: '#784008',
          900: '#502C04',
        },
        teal: {
          glow: '#2DD4BF',
          deep: '#0F766E',
        },
        midnight: '#060818',
        night: '#0A0E27',
        deepspace: '#0D1230',
        starlight: '#E8EAF6',
        moonlight: '#C4D0F0',
        silver: '#B8C4E8',
      },
      fontFamily: {
        serif: ['"Cinzel"', 'serif'],
        script: ['"Cormorant Garamond"', 'serif'],
        sans: ['"Outfit"', 'sans-serif'],
        magic: ['"Cinzel Decorative"', 'serif'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 10s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
        'spin-slow': 'spin-slow 30s linear infinite',
        'spin-slower': 'spin-slow 60s linear infinite',
        'spin-reverse': 'spin-reverse 45s linear infinite',
        'zoom-bg': 'zoomBg 25s ease-in-out infinite alternate',
        'shimmer': 'shimmer 3s linear infinite',
        'glow': 'glow 2.5s ease-in-out infinite',
        'glow-strong': 'glowStrong 2s ease-in-out infinite',
        'fall': 'fall linear infinite',
        'sway': 'sway 5s ease-in-out infinite',
        'fade-in': 'fadeIn 1.5s ease-out forwards',
        'slide-up': 'slideUp 1s ease-out forwards',
        'mist': 'mist 15s ease-in-out infinite',
        'mist-slow': 'mist 25s ease-in-out infinite',
        'twinkle': 'twinkle 3s ease-in-out infinite',
        'orbit': 'orbit 20s linear infinite',
        'flicker': 'flicker 4s ease-in-out infinite',
        'breathe': 'breathe 4s ease-in-out infinite',
        'scroll-hint': 'scrollHint 2s ease-in-out infinite',
        'rune-glow': 'runeGlow 3s ease-in-out infinite',
        'portal': 'portal 8s linear infinite',
        'wave': 'wave 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        'pulse-soft': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.15)', opacity: '1', filter: 'drop-shadow(0 0 20px rgba(160,111,255,0.7))' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'spin-reverse': {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        zoomBg: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.15)' },
          '100%': { transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(160,111,255,0.3)' },
          '50%': { boxShadow: '0 0 50px rgba(160,111,255,0.7)' },
        },
        'glow-strong': {
          '0%, 100%': { filter: 'drop-shadow(0 0 10px rgba(45,212,191,0.5))' },
          '50%': { filter: 'drop-shadow(0 0 30px rgba(45,212,191,0.9))' },
        },
        fall: {
          '0%': { transform: 'translateY(-5vh) translateX(0) scale(0.5)', opacity: '0' },
          '10%': { opacity: '0.9', transform: 'translateY(0vh) translateX(5px) scale(1)' },
          '50%': { transform: 'translateY(50vh) translateX(-10px) scale(1)' },
          '90%': { opacity: '0.9', transform: 'translateY(100vh) translateX(15px) scale(1)' },
          '100%': { transform: 'translateY(105vh) translateX(0) scale(0.5)', opacity: '0' },
        },
        sway: {
          '0%, 100%': { transform: 'translateX(-20px)' },
          '50%': { transform: 'translateX(20px)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        mist: {
          '0%, 100%': { transform: 'translateX(-10%) scale(1)', opacity: '0.3' },
          '50%': { transform: 'translateX(10%) scale(1.2)', opacity: '0.5' },
        },
        twinkle: {
          '0%, 100%': { opacity: '0.2', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.2)' },
        },
        orbit: {
          '0%': { transform: 'rotate(0deg) translateX(80px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(80px) rotate(-360deg)' },
        },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '25%': { opacity: '0.8' },
          '50%': { opacity: '0.95' },
          '75%': { opacity: '0.7' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.6' },
          '50%': { transform: 'scale(1.05)', opacity: '0.9' },
        },
        'scroll-hint': {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.5' },
          '50%': { transform: 'translateY(10px)', opacity: '1' },
        },
        'rune-glow': {
          '0%, 100%': { opacity: '0.4', filter: 'drop-shadow(0 0 5px rgba(160,111,255,0.3))' },
          '50%': { opacity: '1', filter: 'drop-shadow(0 0 20px rgba(160,111,255,0.8))' },
        },
        portal: {
          '0%': { transform: 'rotate(0deg) scale(1)', opacity: '0.6' },
          '50%': { transform: 'rotate(180deg) scale(1.1)', opacity: '1' },
          '100%': { transform: 'rotate(360deg) scale(1)', opacity: '0.6' },
        },
        wave: {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%': { transform: 'scaleY(1)' },
        },
      },
    },
  },
  plugins: [],
};
