/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        rose: {
          50: '#FFF5F7',
          100: '#FFE8EC',
          200: '#FFD0D9',
          300: '#FFB3C1',
          400: '#FF8FA3',
          500: '#F06B85',
          600: '#D04E6B',
          700: '#A83A52',
          800: '#7A2A3D',
          900: '#4D1A28',
        },
        lavender: {
          50: '#F8F6FF',
          100: '#EDE9FF',
          200: '#DDD6FF',
          300: '#C7BCFF',
          400: '#A99BFF',
          500: '#8B7BF5',
          600: '#6E5DD9',
          700: '#5644B0',
          800: '#3E3280',
          900: '#28205A',
        },
        sage: {
          50: '#F5F8F5',
          100: '#E8F0E8',
          200: '#C8DDD8',
          300: '#A0C4B8',
          400: '#7AAB98',
          500: '#5C9079',
          600: '#467560',
          700: '#365A4A',
          800: '#243D33',
          900: '#152620',
        },
        gold: {
          soft: '#E8C49A',
          light: '#F0D4B0',
          medium: '#D4A574',
          deep: '#B8884F',
        },
        cream: '#FAF6F0',
        blush: '#FFF0F3',
        petal: '#FFE4EC',
        silk: '#F9F5F0',
        mist: '#F0EBE6',
        ink: '#2A2025',
        inksoft: '#3D3036',
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', 'serif'],
        script: ['"Great Vibes"', 'cursive'],
        sans: ['"Outfit"', 'sans-serif'],
        display: ['"Playfair Display"', 'serif'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 10s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 4s ease-in-out infinite',
        'spin-slow': 'spin-slow 40s linear infinite',
        'spin-slower': 'spin-slow 80s linear infinite',
        'spin-reverse': 'spin-reverse 60s linear infinite',
        'zoom-bg': 'zoomBg 30s ease-in-out infinite alternate',
        'shimmer': 'shimmer 4s linear infinite',
        'glow': 'glow 3s ease-in-out infinite',
        'fall': 'fall linear infinite',
        'sway': 'sway 6s ease-in-out infinite',
        'fade-in': 'fadeIn 2s ease-out forwards',
        'slide-up': 'slideUp 1.2s ease-out forwards',
        'twinkle': 'twinkle 4s ease-in-out infinite',
        'breathe': 'breathe 5s ease-in-out infinite',
        'scroll-hint': 'scrollHint 2.5s ease-in-out infinite',
        'petal-fall': 'petalFall linear infinite',
        'soft-pulse': 'softPulse 5s ease-in-out infinite',
        'page-turn': 'pageTurn 1.5s ease-in-out forwards',
        'curtain-up': 'curtainUp 2s cubic-bezier(0.65, 0, 0.35, 1) forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        'pulse-soft': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.7' },
          '50%': { transform: 'scale(1.1)', opacity: '1', filter: 'drop-shadow(0 0 15px rgba(240,212,176,0.5))' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'spin-reverse': {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        zoomBg: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.12)' },
          '100%': { transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(232,196,154,0.2)' },
          '50%': { boxShadow: '0 0 35px rgba(232,196,154,0.4)' },
        },
        fall: {
          '0%': { transform: 'translateY(-5vh) translateX(0) rotate(0deg) scale(0.5)', opacity: '0' },
          '10%': { opacity: '0.8', transform: 'translateY(0vh) translateX(10px) rotate(45deg) scale(1)' },
          '50%': { transform: 'translateY(50vh) translateX(-15px) rotate(180deg) scale(1)' },
          '90%': { opacity: '0.8', transform: 'translateY(100vh) translateX(20px) rotate(315deg) scale(1)' },
          '100%': { transform: 'translateY(105vh) translateX(0) rotate(360deg) scale(0.5)', opacity: '0' },
        },
        sway: {
          '0%, 100%': { transform: 'translateX(-15px)' },
          '50%': { transform: 'translateX(15px)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        twinkle: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(0.8)' },
          '50%': { opacity: '0.9', transform: 'scale(1.2)' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.6' },
          '50%': { transform: 'scale(1.05)', opacity: '0.9' },
        },
        'scroll-hint': {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '50%': { transform: 'translateY(10px)', opacity: '0.8' },
        },
        'petal-fall': {
          '0%': { transform: 'translateY(-5vh) translateX(0) rotate(0deg)', opacity: '0' },
          '15%': { opacity: '0.8' },
          '50%': { transform: 'translateY(50vh) translateX(30px) rotate(180deg)' },
          '85%': { opacity: '0.8' },
          '100%': { transform: 'translateY(105vh) translateX(-20px) rotate(360deg)', opacity: '0' },
        },
        'soft-pulse': {
          '0%, 100%': { opacity: '0.5', transform: 'scale(1)' },
          '50%': { opacity: '0.9', transform: 'scale(1.08)' },
        },
        'page-turn': {
          '0%': { transform: 'perspective(2000px) rotateY(0deg)', opacity: '1' },
          '50%': { transform: 'perspective(2000px) rotateY(-15deg)', opacity: '0.8' },
          '100%': { transform: 'perspective(2000px) rotateY(-90deg)', opacity: '0' },
        },
        'curtain-up': {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-100%)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
